name: ${HOMELAB_PROJECT_NAME:-homelab}

include:
  - modules/core/compose.yaml
  - modules/monitoring/compose.yaml
  - modules/tools/compose.yaml
  - modules/iot/compose.yaml
  - modules/uptime/compose.yaml
  - modules/dns/compose.yaml
  - modules/dashboard/compose.yaml
  - modules/auth/compose.yaml
  - modules/logs/compose.yaml

networks:
  proxy:
    name: ${HOMELAB_PROJECT_NAME:-homelab}_proxy
  backend:
    name: ${HOMELAB_PROJECT_NAME:-homelab}_backend
    internal: true
  socket:
    name: ${HOMELAB_PROJECT_NAME:-homelab}_socket
    internal: true
  iot:
    name: ${HOMELAB_PROJECT_NAME:-homelab}_iot

volumes:
  influxdb_data:
    name: ${HOMELAB_PROJECT_NAME:-homelab}_influxdb_data
  influxdb_config:
    name: ${HOMELAB_PROJECT_NAME:-homelab}_influxdb_config
  grafana_data:
    name: ${HOMELAB_PROJECT_NAME:-homelab}_grafana_data
  portainer_data:
    name: ${HOMELAB_PROJECT_NAME:-homelab}_portainer_data
  netdata_config:
    name: ${HOMELAB_PROJECT_NAME:-homelab}_netdata_config
  netdata_lib:
    name: ${HOMELAB_PROJECT_NAME:-homelab}_netdata_lib
  netdata_cache:
    name: ${HOMELAB_PROJECT_NAME:-homelab}_netdata_cache
  mosquitto_data:
    name: ${HOMELAB_PROJECT_NAME:-homelab}_mosquitto_data
  openhab_addons:
    name: ${HOMELAB_PROJECT_NAME:-homelab}_openhab_addons
  openhab_conf:
    name: ${HOMELAB_PROJECT_NAME:-homelab}_openhab_conf
  openhab_userdata:
    name: ${HOMELAB_PROJECT_NAME:-homelab}_openhab_userdata
  uptime_kuma_data:
    name: ${HOMELAB_PROJECT_NAME:-homelab}_uptime_kuma_data
  adguard_work:
    name: ${HOMELAB_PROJECT_NAME:-homelab}_adguard_work
  adguard_config:
    name: ${HOMELAB_PROJECT_NAME:-homelab}_adguard_config
  authelia_data:
    name: ${HOMELAB_PROJECT_NAME:-homelab}_authelia_data

secrets:
  influxdb_username:
    file: ./.secrets/influxdb_username
  influxdb_password:
    file: ./.secrets/influxdb_password
  influxdb_token:
    file: ./.secrets/influxdb_token
  grafana_admin_password:
    file: ./.secrets/grafana_admin_password
  traefik_users:
    file: ./.secrets/traefik_users
  mosquitto_passwords:
    file: ./.secrets/mosquitto_passwords
