---
- resources:
    cpu: true
    memory: true
    disk: /
    expanded: true
    label: Dashboard host
- search:
    provider: duckduckgo
    target: _blank
- datetime:
    format:
      dateStyle: long
      timeStyle: short
      hour12: false
