#!/usr/bin/env python3
"""Initialize local configuration for opt-in community services."""

from __future__ import annotations

import os
import re
import secrets
import stat
import subprocess
import sys
from pathlib import Path

import doctor

ROOT = Path(__file__).resolve().parents[1]
SECRETS = ROOT / ".secrets"
HTPASSWD_IMAGE = "httpd:2.4.68-alpine"
USERNAME_RE = re.compile(r"^[a-z0-9][a-z0-9_.-]*$")
EMAIL_RE = re.compile(r"^[^\s@]+@[^\s@]+\.[^\s@]+$")


class CommunityInitError(RuntimeError):
    """Raised when community initialization cannot proceed safely."""


def validate_auth_domain(value: str) -> str:
    domain = value.strip().lower()
    if not doctor.valid_domain(domain) or domain == "localhost" or "." not in domain:
        raise CommunityInitError(
            "Authelia requires a normal domain with at least one dot; localhost is not supported"
        )
    return domain


def _yaml_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render_authelia_configuration(domain: str, timezone: str) -> str:
    domain = validate_auth_domain(domain)
    return f"""# Generated by scripts/init_community.py. Re-run make auth-init after changing BASE_DOMAIN.
server:
  address: tcp4://0.0.0.0:9091
  endpoints:
    authz:
      forward-auth:
        implementation: ForwardAuth

log:
  level: info

theme: auto

identity_validation:
  reset_password:
    jwt_lifespan: 5m

authentication_backend:
  password_reset:
    disable: true
  file:
    path: /config/users_database.yml
    watch: false
    password:
      algorithm: bcrypt
      bcrypt:
        variant: standard
        cost: 12

access_control:
  default_policy: deny
  rules:
    - domain: '*.{domain}'
      policy: one_factor

session:
  name: authelia_session
  same_site: lax
  inactivity: 5m
  expiration: 1h
  remember_me: 1M
  cookies:
    - domain: {domain}
      authelia_url: https://auth.{domain}
      default_redirection_url: https://home.{domain}

regulation:
  max_retries: 4
  find_time: 2m
  ban_time: 5m

storage:
  local:
    path: /data/db.sqlite3

notifier:
  disable_startup_check: false
  filesystem:
    filename: /data/notification.txt

telemetry:
  metrics:
    enabled: false

ntp:
  address: time.cloudflare.com:123
  version: 4
  max_desync: 3s
  disable_startup_check: false

# Operator timezone: {timezone}
"""


def render_authelia_users(
    *,
    username: str,
    display_name: str,
    email: str,
    password_hash: str,
) -> str:
    if USERNAME_RE.fullmatch(username) is None:
        raise CommunityInitError("AUTHELIA_USERNAME contains unsupported characters")
    if EMAIL_RE.fullmatch(email) is None:
        raise CommunityInitError("AUTHELIA_EMAIL is invalid")
    if not password_hash.startswith(("$2y$12$", "$2b$12$", "$2a$12$")):
        raise CommunityInitError("Authelia user password must be a cost-12 bcrypt hash")
    return f"""# yaml-language-server: $schema=https://www.authelia.com/schemas/latest/json-schema/user-database.json
users:
  {username}:
    disabled: false
    displayname: {_yaml_quote(display_name)}
    password: {_yaml_quote(password_hash)}
    email: {_yaml_quote(email)}
    groups:
      - admins
"""


def hash_command(username: str) -> list[str]:
    if USERNAME_RE.fullmatch(username) is None:
        raise CommunityInitError("AUTHELIA_USERNAME contains unsupported characters")
    return [
        "docker",
        "run",
        "--rm",
        "-i",
        "--entrypoint",
        "htpasswd",
        HTPASSWD_IMAGE,
        "-n",
        "-i",
        "-B",
        "-C",
        "12",
        username,
    ]


def _write_new(path: Path, value: str, mode: int, *, newline: bool = False) -> bool:
    if path.exists():
        if not path.is_file() or path.is_symlink():
            raise CommunityInitError(f"{path.relative_to(ROOT)} exists but is not a regular file")
        return False
    data = value + ("\n" if newline else "")
    path.write_text(data, encoding="utf-8")
    path.chmod(mode)
    return True


def _random_secret() -> str:
    return secrets.token_urlsafe(64)


def _hash_password(username: str, password: str) -> str:
    try:
        result = subprocess.run(
            hash_command(username),
            cwd=ROOT,
            input=f"{password}\n",
            check=False,
            capture_output=True,
            text=True,
            timeout=120,
        )
    except FileNotFoundError as exc:
        raise CommunityInitError("Docker CLI is required to create the Authelia user hash") from exc
    if result.returncode != 0:
        detail = result.stderr.strip() or "htpasswd failed"
        raise CommunityInitError(detail)
    record = result.stdout.strip()
    prefix = f"{username}:"
    if not record.startswith(prefix):
        raise CommunityInitError("htpasswd returned an unexpected username")
    password_hash = record[len(prefix):]
    if not password_hash.startswith(("$2y$12$", "$2b$12$", "$2a$12$")):
        raise CommunityInitError("htpasswd did not return a cost-12 bcrypt hash")
    return password_hash


def _load_env() -> dict[str, str]:
    path = ROOT / ".env"
    if not path.is_file():
        raise CommunityInitError("run `make init` before `make auth-init`")
    return doctor.read_env(path)


def main() -> int:
    try:
        env = _load_env()
        domain = validate_auth_domain(env.get("BASE_DOMAIN", "localhost"))
        timezone = env.get("TZ", "Etc/UTC")
        username = env.get("AUTHELIA_USERNAME", "admin")
        display_name = env.get("AUTHELIA_DISPLAY_NAME", "Homelab Administrator")
        email = env.get("AUTHELIA_EMAIL", f"{username}@{domain}")

        if not SECRETS.is_dir():
            raise CommunityInitError("run `make init` before `make auth-init`")
        mode = SECRETS.stat().st_mode & 0o777
        if mode != 0o700:
            raise CommunityInitError(f".secrets mode is {mode:04o}, expected 0700")

        username_path = SECRETS / "authelia_username"
        if username_path.exists():
            stored_username = username_path.read_text(encoding="utf-8").strip()
            if stored_username != username:
                raise CommunityInitError(
                    "AUTHELIA_USERNAME differs from the initialized user; rotate deliberately or restore the previous setting"
                )
        else:
            _write_new(username_path, username, 0o600)

        password_path = SECRETS / "authelia_password"
        if not password_path.exists():
            _write_new(password_path, secrets.token_urlsafe(24), 0o600)
        password = password_path.read_text(encoding="utf-8").strip()
        if not password:
            raise CommunityInitError("authelia_password is empty")

        for name in (
            "authelia_session_secret",
            "authelia_storage_encryption_key",
            "authelia_jwt_secret",
        ):
            _write_new(SECRETS / name, _random_secret(), 0o600)

        users_path = SECRETS / "authelia_users.yml"
        if not users_path.exists():
            password_hash = _hash_password(username, password)
            users = render_authelia_users(
                username=username,
                display_name=display_name,
                email=email,
                password_hash=password_hash,
            )
            _write_new(users_path, users.rstrip("\n"), 0o644, newline=True)

        configuration = render_authelia_configuration(domain, timezone)
        config_path = SECRETS / "authelia_configuration.yml"
        temporary = SECRETS / ".authelia_configuration.yml.tmp"
        temporary.write_text(configuration, encoding="utf-8")
        temporary.chmod(0o644)
        os.replace(temporary, config_path)

        for name in (
            "authelia_password",
            "authelia_session_secret",
            "authelia_storage_encryption_key",
            "authelia_jwt_secret",
            "authelia_username",
        ):
            (SECRETS / name).chmod(0o600)
        users_path.chmod(0o644)
        config_path.chmod(0o644)

        print(f"Authelia configuration initialized for https://auth.{domain}")
        print("Read the initial password with: cat .secrets/authelia_password")
        return 0
    except (CommunityInitError, OSError, UnicodeError) as exc:
        print(f"Community initialization failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
